site_name: FReSH - France Recherche en Santé Humaine
site_url: https://portail-fresh.github.io/technical-documentation/fr/DocumentationTechnique/

markdown_extensions :
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
nav:

  - Français :
    - Documentation technique: fr/DocumentationTechnique.md
    - Dictionnaire des variables :
      - Présentation : fr/DictionnaireVariables/DictionnaireVariables.md
      - Sections:
        - 0. Métadonnées techniques: fr/DictionnaireVariables/Section_0.md
        - 1. Informations relatives à l'étude: fr/DictionnaireVariables/Section_1.md
        - 2. Renseignements administratifs : fr/DictionnaireVariables/Section_2.md
        - 3. Méthodologie de l'étude : fr/DictionnaireVariables/Section_3.md
        - 4. Collecte et accès aux données : fr/DictionnaireVariables/Section_4.md
    - Vocabulaires contrôlés: fr/VocabulairesControles/VocabulairesControles.md  
    - Schéma des métadonnées : fr/SchemaMetadonnees.md
      
  - English :
    - Technical Documentation : en/TechnicalDocumentation.md
    - Variable dictionnary:
      - Introduction: en/VariablesDictionnary/VariablesDictionnary.md
      - Sections:
        - 0. Technical metadata: en/VariablesDictionnary/Section_0.md
        - 1. Study related information: en/VariablesDictionnary/Section_1.md
        - 2. Administrative information : en/VariablesDictionnary/Section_2.md
        - 3. Study methodology : en/VariablesDictionnary/Section_3.md
        - 4. Data collection and access : en/VariablesDictionnary/Section_4.md
    - FReSH Metadata schema: en/MetadataSchema.md
    - Controlled vocabularies: en/ControlledVocabularies/ControlledVocabularies.md

  - portail-fresh.fr : https://portail-fresh.fr/
  - github.com/portail-fresh : https://github.com/portail-fresh/fresh-metadata-schema/tree/main 
theme:
  name: material
  palette:
    primary: custom
  logo: assets/logo-white - Copie.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes

extra_css:
  - stylesheets/extra.css

# extra:
#   alternate:
#     - name: English
#       link: https://portail-fresh.github.io/technical-documentation/MetadataSchemaIntroEN/
#       lang: en
#     - name: Français
#       link: https://portail-fresh.github.io/technical-documentation/
#       lang: fr
